package com.sample.rules12

import java.util.Date;
import com.sample.Person;

//declare Person
//    name:String
//    age:Integer
//end

rule Entry
    when
    then
        System.out.println("Entry!");
end

rule hello
    when 
        Person(name:name)
    then
        System.out.println("Hello "+name);
end

rule grow
    when 
        p:Person()
    then
        System.out.println("Grow "+p.getName());
        p.setAge(p.getAge()+1);
end

